
import { jsPDF } from 'jspdf';

// Define the Alef font for Hebrew text support
// Base64 representation of Alef-Regular.ttf
// This is a partial implementation - in production you'd use the full font data
const ALEF_FONT_BASE64 = 'AAEAAAATAQAABAAwRkZUTVy1pdQAAKfcAAAAHEdERUYAJwD1AACnwAAAAB5PUy8yVe6H3gAAAWgAAABgY21hcIQdAgsAAAK4AAABwmN2dCAHYB9kAACqpAAAACRmcGdtc/WVmAAAoXgAAAmYZ2FzcAAAABAAAACkAAAACGdseWYXFwV7AAADfAAAiNRoZWFkBx798wAAAQwAAAA2aGhlYQg3A4EAAAFEAAAAJGhtdHgagBnUAAAB6AAAAYpsb2NhvzTUegAAqsgAAADObWF4cAE6AH4AAAFYAAAAIG5hbWUuk0zwAAClEAAAAgVwb3N0/58AMwAAp1gAAAAgcHJlcJxjf3gAAKqUAAAAHgABAAAAAQAA+9nT2l8PPPUACwPoAAAAAMt71TMAAAAAvj80AwAA/zgDAAMnAAAACAACAAAAAAAAAAEAAAMn/zgAAAMAAAADWAMAAAAAAAABAAAAAAAAAAAAAAAAAAAAYQABAAABTgBmAAcAAAAAAAIAAAABAAEAAABAAAAAAAAAAAIBLAGQAAUABAK8AooAAACMArwCigAAAd0AMgD6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQZkVkAEAAIABuAyD/OABkAycAyAAAAAEAAAAAA+gCvAAAACAAAgAAAAMAAAADAAAAHAABAAAAAAC8AAMAAQAAABwABADgAAAANAAgAAQAFAAAACAAIQAzAGYAaQB0AHsAfQCgAKQApgCpALIAtADVANcA2QD+AUEBQwFLAWcBbgBu//8AAAAgACEAMABPAGkAdAB7AH0AoACkAKYAqQCyALQA1QDXANkA/gFBAUMBSwFnAW4Abv///+H/4P/i/9L/1P/K/8T/w/+i/5//nv+c/5T/k/90/3P/cv9O/wz/C/8E/+n/4wBiAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAADIAMgAyADIAMgAyADIA0gEOAcwCuAL8A5YD6AQaBDQEbgSiBNQFAAU4BXQFrgXWBfoGOAZ4BsIHDAcmB2AHpAfYCBwIMAhaCIIIpgjoCPwJHAk6CW4JngmyCcoJ4AoeClIKlgqyCsIK2gr4CxQLNAtKC2ALmguyC9QL5gwCDDYMVgyODMgM+A0kDUoNdA2WDb4N3A4QDjwOYA6ADo4Ong6yDtgO9g8OD0YPdA+iD9AQEAAAAAAAGgAAADgAAAAAAAEAAwABAAAAHAAEAMwAAAAqACAABAAKAAAAIAApADQAVQBpAHQAewB9AKAApACmAKkAsgC0ANUA1wDZAP4BQf//AAAAAAAhADEANQBXAGkAdAB7AH0AoACkAKYAqQCyALQA1QDXANkA/gFB//8AAP/j/93/3P/b/9D/x//A/7//vv+9/7z/u/+6/7n/uf+4/7f/t/9xAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEGAAABAAAAAAAAAAECAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALABFAAAAAACuAK4AjgCuAIAAggCsAIYAZACKAIwAlABmAJgAmgCQAGgAgABqAGwAbgCWAJIAnACeAHYAeAB6AKAAogCkAKYAqACqAGIArAASABQABAAGAAgACgAMAA4AEAAeABAAHABwAHIAdAB2AHgAegB8AH4AgACCAIQAhgCIAHwAigCMAI4AbACqAD4APABAAEIARABGAEgASgBMAFAAeABOAHAAkACQAJIAlACWAJgAmgCcAJ4AoACiAKQApgCoAEoAFgAYABoAHABMAGIAZABmAGgAagBsAG4AcAByAHQAVABWAFgAWgBcAF4AYABiAGQAZgBoAGoAbABuAHAAcgAAADQANgA4ADwAPgBAAEIARABGAEgASgBMAE4AUABSAFQAVgBYAFoAXABeAGAAYgBkAGYAaABqAGwANQA3ADkAOgA7AD0APwBBAEMAiACJAIUAjAAyADMAIQAAAAIARQCLAMkA+QEPARcBOgFCAWUBdwGXAbEB0wHbAfECCQIhAjcCRwJqAoICmgK8As4C5gL+AxYDMANEA2IDggOaA7gD2APyBA0ELQRLBF8EcgSLBKMEugTPBOUE7QULBSMFOwVGBVoFbgV9BY8FrwXHBdkF9AYWBi4GVgZiBnoGiAajBsQG4gb5BwwHHQcrB0AHUgdbB2UHdweEB6IHwAfXB+gAAQAAAGEAcgADAAAAAAACAAEAAgBmAAABAA7OAAAAAAAAABYATgBgAJAAngDgARwBMAFkAsgC+gOAA+oEXAS0BP4FbAXYBhIGTgZ0BoIGxgb8B5wHsAgeCFgIigkACQwJHglICWYJoAmuCcgKGgpkCrILEAtGC24LsAvUC+4MJgxkDJoMwgzmDRQNSg1qDaoN6g4oDp4O0A8GDz4Pdg+kD+YQPhBwEKwRBhFIEX4RoBHGEegSEhJAEmwSkhKsEtgS+hMcEz4TZhOIE6oTzhPqFBYUOBRaFHwUmBUSFUIAAQAAAAEAABhgMi9fDzz1AAsD6AAAAM/fvd0AAAAAz9+93QAA/zgDAAMnAAAACAACAAAAAAAAAAEAAAMn/zgAAAMAAAADWAMAAQAAAAAAAAAAAAAAAAAAAGEAAFAAAAAAAmYCZgAGAAAAAAAAAgAAAAEAAQAAAEAAAAAAAAAA';

/**
 * Function to configure jsPDF for Hebrew text support using the Alef font
 */
export const configureHebrewFont = (pdf: jsPDF): void => {
  try {
    console.log("Configuring PDF for Hebrew text support with Alef font");
    
    // Add the Alef font to the PDF's virtual file system
    pdf.addFileToVFS('Alef-Regular.ttf', ALEF_FONT_BASE64);
    pdf.addFont('Alef-Regular.ttf', 'Alef', 'normal');
    
    // Set RTL mode for Hebrew text direction
    pdf.setR2L(true);
    
    // Set font to Alef for Hebrew support
    pdf.setFont('Alef');
    
    // Add PDF metadata with Hebrew titles
    pdf.setProperties({
      title: 'הצהרת בריאות',
      subject: 'הצהרת בריאות',
      creator: 'מערכת ניהול'
    });
    
    // Increase font size slightly for better readability with Hebrew text
    pdf.setFontSize(14);
    
    // Set line height for better spacing with Hebrew text
    // @ts-ignore - property exists but might not be in types
    if (pdf.setLineHeightFactor) {
      pdf.setLineHeightFactor(1.5);
    }
    
    // Set text color to ensure better contrast
    pdf.setTextColor(0, 0, 0);
    
    console.log("Alef font configuration applied with RTL support");
  } catch (error) {
    console.error("Error configuring Hebrew font:", error);
    // Fallback to basic configuration
    pdf.setR2L(true);
    pdf.setFont('helvetica');
    console.log("Falling back to helvetica font");
  }
}
