// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdqtfghbvxslpyxmsjag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcXRmZ2hidnhzbHB5eG1zamFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjYxMTMsImV4cCI6MjA2MTQ0MjExM30.HbnCHYFre4zOz1iU4DQHXog0RT522BhgDQhTtuIooyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);